package com.ayantsoft.hibernate.pojo;
// Generated 12 Jan, 2018 12:50:12 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Item generated by hbm2java
 */
@Entity
@Table(name = "Item", catalog = "Inventory")
public class Item implements java.io.Serializable {

	private Integer PId;
	private String name;
	private Long costPrice;
	private Long sellPrice;

	public Item() {
	}

	public Item(String name, Long costPrice, Long sellPrice) {
		this.name = name;
		this.costPrice = costPrice;
		this.sellPrice = sellPrice;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "p_id", unique = true, nullable = false)
	public Integer getPId() {
		return this.PId;
	}

	public void setPId(Integer PId) {
		this.PId = PId;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "costPrice", precision = 10, scale = 0)
	public Long getCostPrice() {
		return this.costPrice;
	}

	public void setCostPrice(Long costPrice) {
		this.costPrice = costPrice;
	}

	@Column(name = "sellPrice", precision = 10, scale = 0)
	public Long getSellPrice() {
		return this.sellPrice;
	}

	public void setSellPrice(Long sellPrice) {
		this.sellPrice = sellPrice;
	}

}
